name: example-environment
channels:
  - conda-forge
dependencies:
  - pip==23.2.1
  - python==3.10.13
  - matplotlib==3.7.3
  - cartopy==0.21.1
  - numpy==1.26.0
  - pandas=2.0.3
  - plotly==5.9.0
  - shapely==2.0.1
  - nbformat==5.9.2